### ISSUE TITLE
npm run dev is invalid

### ISSUE THREAD

**Issue by sobolevn** [Developmint/vue-link#3]
Your `package.json` specifies `dev` script as follows: `nuxt test/fixture`.
But there are two issues with that:
1. `nuxt` is missing from `devDependencies`
2. `test/fixture` is missing from source control

I am not sure what to do with this issue, so I will leave everything as it is while working on #2

**Comment by manniL** [comment]
Oops, this was a leftover from initializing the repository! There is no `dev` command at the moment. Only `test` to run the unit tests.

But I guess it wouldn't hurt to provide examples, maybe through [`vue-play`](https://github.com/vue-play/vue-play)
