### ISSUE TITLE
CONTRIBUTING.md file misses information about making commits

### ISSUE THREAD

**Issue by sobolevn** [Developmint/vue-link#4]
As I can see from [your commits](https://github.com/Developmint/vue-link/commits/master), you are using `commitezen` or similar tool to make commits.

And you also lint commits with `commitlint` afterwards. 
But the docs misses that part.

So, it would be very nice for future contributors to add a note about it.

**Comment by manniL** [comment]
You are right, I'm using a specific commit message structure, though I don't use any tools for it.

I've added a short paragraph about [conventional commits](http://conventionalcommits.org/) in the `CONTRIBUTING.md` :)

Thanks for the hint!
